services:
  - type: web
    name: afkbuilder_api
    env: node
    plan: free
    repo: https://github.com/Dae314/afkbuilder_api.git
    region: ohio
    branch: master
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 16.13.1
      - key: NODE_ENV
        value: production
      - key: BUILD_TYPE
        value: production
      - key: PORT
        value: 16011
      - key: DATABASE_URL
        fromDatabase:
          name: afkbuilder_strapi
          property: connectionString
      - key: CRON_ENABLED
        value: true
      - key: DEFAULT_USER_ID
        value: 1
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: APP_KEYS
        sync: false

databases:
  - name: afkbuilder_strapi
    plan: free
